# Generated by Django 5.0.3 on 2024-05-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_preferences_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='preferences',
            field=models.CharField(choices=[('byGender', 'ByGender')], default='gender_algorithm', max_length=100),
        ),
    ]
